### ISSUE TITLE
MySQL 8.0.1 removes suport for the my_bool type

### ISSUE THREAD

**Issue by aharisu** [kahua/Gauche-dbd-mysql#5]
Incompatible changes in MySQL 8.0.1 [https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling)

Error:
```
dbd_mysql.c:382:45: error: ‘my_bool’ undeclared (first use in this function); did you mean ‘bool’?
  382 |         if ((param->is_null = malloc(sizeof(my_bool))) == NULL)
      |                                             ^~~~~~~
      |                                             bool
dbd_mysql.c:382:45: note: each undeclared identifier is reported only once for each function it appears in
```

Versions:
Gauche scheme shell, version 0.9.7 [utf-8,pthreads], x86_64-pc-linux-gnu
mysql  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64

**Comment by shirok** [comment]
Thanks for reporting.  How about now?

**Comment by aharisu** [comment]
I'm making it work with a simple fix.

``` diff
  #include <mysql.h>
  #include <errmsg.h>
  #include <mysqld_error.h>
+ typedef _Bool my_bool;
```

**Comment by shirok** [comment]
Since they drop `my_bool`, there's no reason for us to keep the name.  If the current HEAD works for you, I'll wrap it as 0.4.1.

**Comment by aharisu** [comment]
HEAD worked fine. thanks you.

Please close this Issue.

**Comment by shirok** [comment]
Thanks.
